In [ ]:
import pandas as pd
import os

In [ ]:
# Conección Drive Datasets
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Lectura primer Dataset
df_1 = pd.read_json("/content/drive/MyDrive/Datasets/Earthquakes_seismic/Dataset_01_D1.ndjson", lines=True)
df_1.head()

,rel_filepath,dt,npts,mag,type,vs,data
0,1 Stiker Slip (SS)/Mag. 4-6/Vs30. 0-200/RSN101...,0.01,27011,Mag. 4-6,SS,Vs30. 0-200,"[4.8407337e-10, 4.7421894e-10, 4.6596636e-10, ..."
1,1 Stiker Slip (SS)/Mag. 4-6/Vs30. 0-200/RSN101...,0.01,27011,Mag. 4-6,SS,Vs30. 0-200,"[-1.8793706e-09, -1.8836359e-09, -1.8907497000..."
2,1 Stiker Slip (SS)/Mag. 4-6/Vs30. 0-200/RSN101...,0.01,27011,Mag. 4-6,SS,Vs30. 0-200,"[5.3919802e-10, 5.3541586e-10, 5.3129373e-10, ..."
3,1 Stiker Slip (SS)/Mag. 4-6/Vs30. 0-200/RSN103...,0.01,19086,Mag. 4-6,SS,Vs30. 0-200,"[8.3309787e-09, 8.374846000000001e-09, 8.40987..."
4,1 Stiker Slip (SS)/Mag. 4-6/Vs30. 0-200/RSN103...,0.01,19086,Mag. 4-6,SS,Vs30. 0-200,"[5.5480786999999994e-11, 5.3899869e-11, 5.1448..."

In [ ]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5319 entries, 0 to 5318
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   rel_filepath  5319 non-null   object
 1   dt            5319 non-null   float64
 2   npts          5319 non-null   int64
 3   mag           5319 non-null   object
 4   type          5319 non-null   object
 5   vs            5319 non-null   object
 6   data          5319 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 291.0+ KB

In [ ]:
# Lectura segundo Dataset
df_2 = pd.read_json("/content/drive/MyDrive/Datasets/Earthquakes_seismic/Dataset_02_D2.ndjson", lines=True)
df_2.head()

,rel_filepath,dt,npts,mag,type,vs,data
0,1 Stiker Slip (SS)/Mag. 4-6/Vs30. 0-200/Compon...,0.01,27011,Mag. 4-6,SS,Vs30. 0-200,"[4.8407337e-10, 4.7421894e-10, 4.6596636e-10, ..."
1,1 Stiker Slip (SS)/Mag. 4-6/Vs30. 0-200/Compon...,0.01,19086,Mag. 4-6,SS,Vs30. 0-200,"[8.3309787e-09, 8.374846000000001e-09, 8.40987..."
2,1 Stiker Slip (SS)/Mag. 4-6/Vs30. 0-200/Compon...,0.01,20001,Mag. 4-6,SS,Vs30. 0-200,"[-2.7771621999999997e-08, -2.8050715e-08, -2.8..."
3,1 Stiker Slip (SS)/Mag. 4-6/Vs30. 0-200/Compon...,0.01,8331,Mag. 4-6,SS,Vs30. 0-200,"[-1.6799257e-08, -1.6793452e-08, -1.6308251e-0..."
4,1 Stiker Slip (SS)/Mag. 4-6/Vs30. 0-200/Compon...,0.01,10036,Mag. 4-6,SS,Vs30. 0-200,"[-1.3724122999999999e-08, -1.3651070999999999e..."

In [ ]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5268 entries, 0 to 5267
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   rel_filepath  5268 non-null   object
 1   dt            5268 non-null   float64
 2   npts          5268 non-null   int64
 3   mag           5268 non-null   object
 4   type          5268 non-null   object
 5   vs            5268 non-null   object
 6   data          5268 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 288.2+ KB

In [ ]:
# Une los dos Datasets
df = pd.concat([df_1, df_2], ignore_index=True)
df.head()

,rel_filepath,dt,npts,mag,type,vs,data
0,1 Stiker Slip (SS)/Mag. 4-6/Vs30. 0-200/RSN101...,0.01,27011,Mag. 4-6,SS,Vs30. 0-200,"[4.8407337e-10, 4.7421894e-10, 4.6596636e-10, ..."
1,1 Stiker Slip (SS)/Mag. 4-6/Vs30. 0-200/RSN101...,0.01,27011,Mag. 4-6,SS,Vs30. 0-200,"[-1.8793706e-09, -1.8836359e-09, -1.8907497000..."
2,1 Stiker Slip (SS)/Mag. 4-6/Vs30. 0-200/RSN101...,0.01,27011,Mag. 4-6,SS,Vs30. 0-200,"[5.3919802e-10, 5.3541586e-10, 5.3129373e-10, ..."
3,1 Stiker Slip (SS)/Mag. 4-6/Vs30. 0-200/RSN103...,0.01,19086,Mag. 4-6,SS,Vs30. 0-200,"[8.3309787e-09, 8.374846000000001e-09, 8.40987..."
4,1 Stiker Slip (SS)/Mag. 4-6/Vs30. 0-200/RSN103...,0.01,19086,Mag. 4-6,SS,Vs30. 0-200,"[5.5480786999999994e-11, 5.3899869e-11, 5.1448..."

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10587 entries, 0 to 10586
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   rel_filepath  10587 non-null  object
 1   dt            10587 non-null  float64
 2   npts          10587 non-null  int64
 3   mag           10587 non-null  object
 4   type          10587 non-null  object
 5   vs            10587 non-null  object
 6   data          10587 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 579.1+ KB

In [ ]:
# Exportar ndjson
output_path = "/content/drive/MyDrive/Datasets/Earthquakes_seismic/Earthquakes_seismic.ndjson"
df.to_json(output_path, orient="records", lines=True)

In [ ]:
print(os.path.exists(output_path))

True